In [1]:
import numpy as np
# np.array? # Getting information from a function
x = np.array([[1, 2], [3, 4]], float) # Creating an array with a list of list
x.shape 

(2, 2)

In [2]:
y = np.array([[1,2], [3,4]], float)
y.sum()
np.sum(y)

10.0

In [23]:
x = np.array([1,2,3,4,5,6], float)
print(x)

[1. 2. 3. 4. 5. 6.]


In [22]:
x_reshape = x.reshape((2,3))
print(x_reshape)

[[10.  2.  3.]
 [ 4.  5.  6.]]


In [17]:
x_reshape[0,0] # First element
x_reshape[1,2] # Last element

6.0

In [29]:
print(x)
x_reshape[0,0] = 10
print(x_reshape)
print(x)

[1. 2. 3. 4. 5. 6.]
[[10.  2.  3.]
 [ 4.  5.  6.]]
[1. 2. 3. 4. 5. 6.]


In [30]:
print(x_reshape.shape)
print(x_reshape.ndim)
print(x_reshape.T)

(2, 3)
2
[[10.  4.]
 [ 2.  5.]
 [ 3.  6.]]


In [40]:
z = np.random.normal(size=50).reshape((50))
print(z)

[ 2.06894456  0.3605498   0.22294809 -0.33327333  1.12330617  0.46682654
 -0.5085224  -0.44338914  0.84407704 -1.63741054  0.41012356  0.53836503
 -0.52362769 -1.16721048  0.02740884  0.04810008  1.30485139 -0.59428765
 -0.68171163  0.98051714  1.23185869  0.6152403  -0.67456623 -1.36515182
  0.63417831  1.25406373 -2.05027915  0.49211762 -0.02219876 -0.09784471
  0.56866248 -1.3226744   0.35665786 -0.44622554  0.20261427  0.94126719
 -0.09584852 -0.75079207  1.0464177  -1.72743782 -0.64283089  0.72855169
  0.83155509 -0.36656493 -0.23750831 -0.72921911  0.12574691  1.04131712
 -0.73878067  1.0255189 ]


In [41]:
xx = z + np.random.normal(loc=50,scale=1,size=50).reshape((50))
print(xx)

[52.52931965 50.06599745 49.38674212 48.18071709 51.2357056  49.90813546
 49.02619997 50.40949134 50.33159324 47.66379513 50.82215416 50.16837794
 50.02747795 49.32084762 48.47231735 50.27432879 50.92375941 50.93643822
 48.15132948 50.3356298  51.08362657 49.98204986 47.42769255 50.10127644
 51.11308328 49.52050634 48.04754094 50.83922698 50.22366127 48.68494129
 49.27986391 48.87633751 50.18050631 49.47462718 50.14850529 50.68522571
 49.64886324 50.66199956 51.58699201 47.61128118 50.03481161 50.66575774
 52.19917362 49.50622249 50.09136785 47.6783053  50.11376123 50.04255132
 49.28785657 49.24726145]


In [42]:
print(np.corrcoef(z,xx))

[[1.         0.67879181]
 [0.67879181 1.        ]]


In [44]:
rng = np.random.default_rng(1303)
print(rng.normal(scale=5, size=2))
rng2 = np.random.default_rng(1303)
print(rng2.normal(scale=5, size=2))

[ 4.09482632 -1.07485605]
[ 4.09482632 -1.07485605]


In [49]:
rng = np.random.default_rng(3)
y = rng.standard_normal(10)
np.mean(y), y.mean()

(-0.1126795190952861, -0.1126795190952861)

In [ ]:
np.var(y), y.var(), np.mean((y - y.mean())**2)
np.sqrt(np.var(y)), np.std(y)
X = rng.standard_normal((10, 3))